<# 

.SYNOPSIS
    CYBERANALYSTVM CONFIGURATION SCRIPT
    Module: Hello Banner
    Author: Diego Perez (@darkquassar)
    Version: 1.0.0
    Description: Presentation Banner 
#>

function Show-Banner {


    # Encoded Banner
    [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String("DQAKACAAXwBfAF8AXwBfACAAXwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAXwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAF8AIAAgACAAXwAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABfAF8AIAAgACAAIAAgACAAIABfACAAIAAgACAAIAANAAoALwBfAF8AIAAgACAAXAAgAHwAXwBfACAAIABfACAAXwBfACAAXwBfAF8AIAAgAF8AXwAgAF8AfAAgAHwAXwAgACAALwBcACAAIAAvAFwAXwAgACAAIABfACAAXwAgAF8AXwAgAHwAIAB8AF8AKABfACkAXwAgAF8AXwAgACAAIABfAF8AIABfACAAIAAvACAALwAgACAAXwBfACAAXwB8ACAAfABfAF8AIAAgAA0ACgAgACAALwAgAC8AXAAvACAAJwBfACAAXAB8ACAAJwBfAF8ALwAgAF8AIABcAC8AIABfAGAAIAB8ACAAXwBfAHwALwAgAC8AXwAvACAALwAgAHwAIAB8ACAAfAAgACcAXwAgAFwAfAAgAF8AXwB8ACAAfAAgACcAXwAgAFwAIAAvACAAXwBgACAAfAAvACAALwAgACAALwAgAF8AYAAgAHwAIAAnAF8AIABcACAADQAKACAALwAgAC8AIAAgAHwAIAB8ACAAfAAgAHwAIAB8ACAAfAAgACAAXwBfAC8AIAAoAF8AfAAgAHwAIAB8AF8ALwAgAF8AXwAgACAALwB8ACAAfABfAHwAIAB8ACAAfAAgAHwAIAB8ACAAfABfAHwAIAB8ACAAfAAgAHwAIAB8ACAAKABfAHwAIAAvACAALwBfAF8AfAAgACgAXwB8ACAAfAAgAHwAXwApACAAfAANAAoAIABcAC8AIAAgACAAfABfAHwAIAB8AF8AfABfAHwAIAAgAFwAXwBfAF8AfABcAF8AXwAsAF8AfABcAF8AXwBcAC8AIAAvAF8ALwAgACAAXABfAF8ALABfAHwAXwB8ACAAfABfAHwAXABfAF8AfABfAHwAXwB8ACAAfABfAHwAXABfAF8ALAAgAFwAXwBfAF8AXwAvAFwAXwBfACwAXwB8AF8ALgBfAF8ALwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB8AF8AXwBfAC8AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABiAHkAIABEAGEAcgBrAFEAdQBhAHMAYQByACwAIABhACAASgBlAGQAeQAtAGYAbABpAHAAcABpAG4AZwAtAHQAYQBiAGwAZQBzACAAZAB1AGQAZQAgACgALgBfAC4AKQAgAH4AIAA1/iAAOyUBJTslDQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAA=="))
    Write-Host "                       ====================================                   "
    Write-Host "                       ==== Starting PowerShell Script ====                   "
    Write-Host "                       ====================================                   "
}